apiVersion: v1
kind: Service
metadata:
  labels:
    app: weather-proxy
    type: web
  name: weather-proxy
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3003
  selector:
    app: weather-proxy
    type: web
  type: LoadBalancer
---
